"""add resolution_source and simulated_attempts to recovery_outcomes

Revision ID: 7ce9337c0a1f
Revises: e9b42bc87b11
Create Date: 2026-08-29 09:16:09.948498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ce9337c0a1f'
down_revision: Union[str, Sequence[str], None] = 'e9b42bc87b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recovery_outcomes', sa.Column('resolution_source', sa.String(), nullable=False))
    op.add_column('recovery_outcomes', sa.Column('simulated_attempts', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recovery_outcomes', 'simulated_attempts')
    op.drop_column('recovery_outcomes', 'resolution_source')
    # ### end Alembic commands ###
