"""add idempotency support: interventions.idempotency_key, webhook_events table

Revision ID: e9b42bc87b11
Revises: d4121f4672e4
Create Date: 2026-08-28 16:37:03.972684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9b42bc87b11'
down_revision: Union[str, Sequence[str], None] = 'd4121f4672e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('razorpay_event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_event_id')
    )
    op.add_column('interventions', sa.Column('idempotency_key', sa.String(), nullable=True))
    op.add_column('interventions', sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('interventions', sa.Column('execution_mode', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'interventions', ['idempotency_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interventions', type_='unique')
    op.drop_column('interventions', 'execution_mode')
    op.drop_column('interventions', 'executed_at')
    op.drop_column('interventions', 'idempotency_key')
    op.drop_table('webhook_events')
    # ### end Alembic commands ###
